[phases.setup]
nixPkgs = ["tzdata", "ffmpeg", "python311", "python311Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install --no-cache-dir -r /app/requirements.txt"]

[variables]
TZ = "Asia/Tokyo"
